name: Build & Deploy

on:
  push:
    branches:
     - master
     - abhisarika

env: 
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 22
          
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./angular17
            
      - name: Build Angular
        run: ng build

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./node-server
        
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./build

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps: 
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/action-gh-pages@v3
        with:
          github_token: ${{secrets.TOKEN}}
          publish_dir: ./build
